<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="chandra" failures="1" tests="5" name="Test" time="6.414" errors="0" timestamp="2022-11-24T11:52:07 IST">
  <testcase classname="com.testng.Retry_concept" name="credencials" time="6.375"/>
  <testcase classname="com.testng.Retry_concept" name="login" time="0.0">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="com.testng.Retry_concept" name="login" time="0.002">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="com.testng.Retry_concept" name="login" time="0.003">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="com.testng.Retry_concept" name="login" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [vanitha] but found [vanitha17]">
      <![CDATA[java.lang.AssertionError: expected [vanitha] but found [vanitha17]
at com.testng.Retry_concept.login(Retry_concept.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
